version: "3"

tasks:
  up:
    interactive: true
    cmds:
      - docker compose up
  down:
    cmds:
      - docker compose down
  watch:
    deps: [up]
    interactive: true
    silent: true
    cmds:
      - docker compose watch
